version: "3.8"
services:
  test-db:
    container_name: test-db
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    stdin_open: false
    tty: false
    ports:
      - 53306:53306
    environment:
      - MYSQL_ROOT_PASSWORD=Root*localhost
      - MYSQL_TCP_PORT=53306
    volumes:
      - G:\dev\java-projects\test-db-data-2:/var/lib/mysql
    networks:
      - test-db-net

networks:
  test-db-net: