name: deploy-and-start-mysql

on:

 workflow_dispatch: 

# pull_request:
#    branches: [ main ]
#    types: [closed]
#    paths:
#      - "keycloak/**"

jobs:

  sftp-artifacts-to-setup-mysql:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
#    needs: [build-test-package]

    steps:
      - uses: actions/checkout@v3

      #  Check out the sftp-to-remote action
      - uses: mp30028/tryout-storage-mgmt/.github/actions/sftp-to-remote@main
        with:
          remote_username: ${{ secrets.REMOTE_USERNAME  }}
          remote_host: ${{ secrets.REMOTE_SERVER  }}
          remote_port: ${{ secrets.REMOTE_PORT  }}
          remote_ssh_key: ${{ secrets.REMOTE_SSH_KEY  }}
          local_filepath: ./mysql-setup
          remote_filepath: ${{ vars.REMOTE_FILEPATH  }}
          
  start-mysql-container:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [sftp-artifacts-to-setup-mysql]

    steps:
      
      #  Check out the sftp-folder-to-remote action
      - uses: mp30028/tryout-storage-mgmt/.github/actions/execute-remote-command@main
        with:
          remote_username: ${{ secrets.REMOTE_USERNAME  }}
          remote_host: ${{ secrets.REMOTE_SERVER  }}
          remote_port: ${{ secrets.REMOTE_PORT  }}
          remote_ssh_key: ${{ secrets.REMOTE_SSH_KEY  }}
          remote_cmd: cd ${{ vars.REMOTE_FILEPATH  }}/mysql-setup; docker compose up -d;